### ISSUE TITLE
Server Console spam: "Does Server pm = new pm? false"

### ISSUE THREAD

**Issue by h454** [CravenCraft/EpicParagliders#11]
I'm not sure what exactly is causing it, but something is causing the following feedback loop:

[18:37:45] [Server thread/INFO] [EpicParagliders/]: --------------- GETTING SKILLS --------------
[18:37:45] [Server thread/INFO] [EpicParagliders/]: Keep skills? false
[18:37:45] [Server thread/INFO] [EpicParagliders/]: Skill: epicfight:basic_attack
[18:37:45] [Server thread/INFO] [EpicParagliders/]: Is skill epicfight:basic_attack replaced? false
[18:37:45] [Server thread/INFO] [EpicParagliders/]: Skill: epicfight:air_attack
[18:37:45] [Server thread/INFO] [EpicParagliders/]: Is skill epicfight:air_attack replaced? true
[18:37:45] [Server thread/INFO] [EpicParagliders/]: Skill: epicfight:sweeping_edge
[18:37:45] [Server thread/INFO] [EpicParagliders/]: Is skill epicfight:sweeping_edge replaced? false
[18:37:45] [Server thread/INFO] [EpicParagliders/]: Skill: epicfight:knockdown_wakeup
[18:37:45] [Server thread/INFO] [EpicParagliders/]: Is skill epicfight:knockdown_wakeup replaced? true
[18:37:45] [Server thread/INFO] [EpicParagliders/]: -----------------------------------------------
* infinity

This occurs about every tick or so? It's persists even after the player dies and keeps happening upon me connecting to my own server. 

Not sure how to fix it, but an idea is that it has to do with how you're going about checking for skills, or whatever your "skill check delay" exactly is.

**Comment by h454** [comment]
A little update:

This seemed to have been triggering non-stop because I opened the skill editor and disconnected at the same time.


Despite that, it floods my console every-time in the menu. Surely there's a nicer way to handle this?

**Comment by CravenCraft** [comment]
Gahhh, these were just loggers that I had to test out how I override the skill system. They were only supposed to display when opening the skill editor and when dying/joining the world/server.

Working on my BetterParagliders mod has made me notice a handful of fairly large bugs in both that mod and this mod. Since Better Combat is less in depth than Epic Fight, I've been focusing on how to restructure my code and fix said bugs on that project to give me a better understanding of how I'm going to tackle this one. Since that mod is currently at a fairly stable state, I can turn my focus towards this one now.

 I'll be working on a fairly large update in the coming weeks to address code restructure, lots of bugs, and smaller things such as this logging issue and attribute support. Once I get those changes pushed I'll close this issue.

**Comment by h454** [comment]
Figured out the why it started doing this:


Your logger spams the server console (for a lack of a better term) when:
1. The player has the Epic Fight skills menu open
2. There are more than two players on a given server.

I think a log request is sent every tick or every other tick or so?
I'd like to mention this incase it helps, idk. Appreciate that you're taking the time to focus on this mod though, but I don't think a patch would be possible without having to install it on all clients, right?
![cmd_kUVx3ghMwK](https://github.com/CravenCraft/EpicParagliders/assets/54318955/dfc9378a-9f9f-4466-a8eb-5e67ca42eeaa)

**Comment by leiske** [comment]
Thanks for acknowledging the issue. Chiming in because we also observed the logs occurring with >=2 players. 

The log was growing (for me) ~3MB a minute which is around ~4-5GB a day assuming >=2 players on. That's a _taaad_ high, but I will cull it more aggressively. Also factor in this logs to both `debug.log` and `latest.log` we're looking at ~8GB - 10GB a day of active use.

Happy to submit a PR that simply comments out the logging, but can also wait patiently for you to address it more in-depth. Promise I'm not rushing you :) 

Appreciate you digging into it!

**Comment by CravenCraft** [comment]
Man, I HATE that I left such a small thing in that just eats up server space. I should be done with my entire rework sometime later tomorrow anyway. So, you shouldn't need to submit the PR.

**Comment by leiske** [comment]
Nothing to beat yourself up over! Again, no rush and really appreciate your responsiveness. Thanks a ton!

**Comment by CravenCraft** [comment]
First commit of my official refactor of the code is here https://github.com/CravenCraft/EpicParagliders/tree/feature/mixin-refactor
So far, still a WIP (with lots of logs for testing still to remove). Should just need to finish up skill support and then I'll be ready to merge into the 1.18.2 release branch. I'll link this issue to the PR when it's ready!
